
# description: gather facts and display
---
- name: STARTING INSTALL PACKAGES
  hosts: "{{ hosts | default('localhost')}}"
  tasks:
    - name: Collect only facts returned by facter
      setup:
        gather_subset:
          - 'all'
    - name: Dump
      delegate_to: localhost
      run_once: true
      copy:
        content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
        dest: /tmp/setup-dump.json
